### ISSUE TITLE
compass install recipes/font-icons not working

### ISSUE THREAD

**Issue by andidev** [MoOx/compass-recipes#53]
I get the following error when trying to install font-icons template

```
termina$ compass install recipes/icon-fonts
SyntaxError on line ["146"] of /Users/anders/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/installers/manifest.rb: /Users/anders/.rvm/gems/ruby-1.9.3-p194/gems/compass-recipes-0.3.0.alpha.2/lib/../templates/icon-fonts/manifest.rb:3: syntax error, unexpected tIDENTIFIER, expecting $end
Run with --trace to see the full backtrace
```

The reason seems to be line 3:

```
directory "fonts/icons" => :within fonts_dir
```

which is not the valid way to import the fonts from a directory (or does it work in latest compass 0.13?). Maybe 

```
discover :fonts
```

could be used instead?

**Comment by chriseppstein** [comment]
``` ruby
directory "fonts/icons", :within  => fonts_dir
```

**Comment by MoOx** [comment]
Thanks @chriseppstein for you help. But with that syntax, I've a fonts_dir undefined error. Can it be a Compass bug ?

```
$ compass install --trace recipes/icon-fonts
NameError on line 3 of /Users/MoOx/Dropbox/Development/compass-recipes/lib/../templates/icon-fonts/manifest.rb: undefined local variable or method `fonts_dir' for #<Compass::Installers::Manifest:0x10dc1d050>
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/installers/manifest.rb:156:in `instance_binding'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/installers/manifest.rb:146:in `parse'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/installers/manifest.rb:145:in `open'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/installers/manifest.rb:145:in `parse'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/installers/manifest.rb:135:in `with_manifest'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/installers/manifest.rb:143:in `parse'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/installers/manifest.rb:20:in `initialize'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/installers/manifest_installer.rb:10:in `new'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/installers/manifest_installer.rb:10:in `initialize'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/app_integration/stand_alone.rb:12:in `new'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/app_integration/stand_alone.rb:12:in `installer'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/commands/installer_command.rb:23:in `installer'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/commands/installer_command.rb:12:in `configure!'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/commands/project_base.rb:15:in `initialize'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/commands/stamp_pattern.rb:69:in `initialize'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/exec/sub_command_ui.rb:42:in `new'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/exec/sub_command_ui.rb:42:in `perform!'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/bin/compass:29
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/bin/compass:43:in `call'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/bin/compass:43
  /usr/bin/compass:19:in `load'
  /usr/bin/compass:19
```

**Comment by andidev** [comment]
This seems to work but it does not copy the files in the directory

   directory "fonts/icons", :within  => "fonts_dir"

@chriseppstein, should it copy the files as well?

**Comment by MoOx** [comment]
It seems it shouldn't.
I'm currently fixing this issue using `discover`.
Expect new release soon.
